### ISSUE TITLE
Border cut

### ISSUE THREAD

**Issue by tormento** [wswartzendruber/pgs-tools#2]
Please add the capability to crop every border with different values.

**Comment by wswartzendruber** [comment]
Apologies, but I am no longer maintaining this project. Truth be told, it doesn't even behave correctly in certain edge cases. The code is under a MPLv2 license, so it can be cloned and taken up by others.

**Comment by wswartzendruber** [comment]
Apologies, but I am no longer maintaining this project. Truth be told, it doesn't even behave correctly in certain edge cases. The code is under a MPLv2 license, so it can be cloned and taken up by others.
